### ISSUE TITLE
Use Batch Tokens

### ISSUE THREAD

**Issue by JustinFullerNYT** [nytimes/gcp-vault#29]
This issue is made in response to the announcement of Vault Throttling.

[Internal discussion](https://nytimes.slack.com/archives/C6950JR54/p1595431519029400), [internal doc with more info](https://docs.google.com/document/d/1xlxWIFhDoHqbDrSx8cD2Oy0dkH6S0KdgbO4F4n--BXk/edit?ts=5f18460c#heading=h.nks8a8l67qma).

Docs:
* [Token Type Comparison](https://www.vaultproject.io/docs/concepts/tokens#token-type-comparison)
* [Token Type Param](https://www.vaultproject.io/api-docs/auth/gcp#token_type)

Ideally, we could make a way for gcp-vault to use batch tokens.

**Comment by brianfoshee** [comment]
Batch tokens are implemented on the vault side so there would likely be no change to gcp-vault, only an update to the policies used to generate the tokens at login. I am working with @alex-khordos and @soeirosantos to see if we can get this working in my team's gae app. However, it would only solve issues 3&4 raised in the internal doc linked above.
